version: "3.8"
services:
  api:
      build: 
        context: '../flskprjct2'
      ports:
          - target: 5353
            published: 5353

      links:
        - web
  web:
    build: 
        context: '../flskprjct'
    ports:
      - target: 5000
        published: 5000 
   

